{% set name = "haystack-experimental" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/haystack_experimental-{{ version }}.tar.gz
  sha256: 6a6ad493dedb717e9e5617b15da0b0c3a352a58540174aaa091b53d166433fa0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.8.0
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - haystack-ai

test:
  imports:
    - haystack_experimental
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/deepset-ai/haystack-experimental
  summary: Experimental components and features for the Haystack LLM framework.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - julian-risch
