{% set name = "haystack-experimental" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/haystack_experimental-{{ version }}.tar.gz
  sha256: 110eb29e8e21790b830d7e23a42e448c6a4d33bcd51ead2175f3a07219512c37

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.8.0
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - haystack-ai

test:
  imports:
    - haystack_experimental
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/deepset-ai/haystack-experimental
  summary: Experimental components and features for the Haystack LLM framework.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - julian-risch
